SithRecruitSystem/urls.py
from django.contrib import admin
from django.urls import path
from SithRecruit import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('results/<int:recruit_id>', views.results, name='results'),
    path('recruit/', views.recruit, name='recruit'),
    path('sith/', views.sith, name='sith'),
    path('recruits_list/', views.recruits_list, name='recruits_list'),
    path('test/', views.test, name='test'),
    path('thank_you/', views.thank_you, name='thank_you')
]

SithRecruit/models.py
from django.db import models


class Planet(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        db_table = 'planet'

    def __str__(self):
        return self.name


class Sith(models.Model):
    name = models.CharField(max_length=200)
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE)

    class Meta:
        db_table = 'sith'

    def __str__(self):
        return self.name


class Question(models.Model):
    text = models.TextField(default='')

    class Meta:
        db_table = 'question'

    def __str__(self):
        return self.text[:15]


class Test(models.Model):
    order_id = models.CharField(max_length=255, unique=True)
    questions = models.ManyToManyField(Question)

    class Meta:
        db_table = 'test'

    def __str__(self):
        return self.order_id[:15]


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.BooleanField()

    class Meta:
        db_table = 'answer'


class Recruit(models.Model):
    name = models.CharField(max_length=200)
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE)
    age = models.PositiveIntegerField()
    email = models.EmailField(unique=True)
    answers = models.ManyToManyField(Answer)
    master_sith = models.ForeignKey(Sith, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'recruit'

    def __str__(self):
        return self.name

SithRecruit/forms.py
from django import forms

from SithRecruit.models import Recruit


class RecruitForm(forms.ModelForm):
    class Meta:
        model = Recruit
        fields = ['planet', 'name', 'age', 'email']

SithRecruit/views.py
from django.core.mail import send_mail
from django.forms.models import model_to_dict
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from SithRecruit.forms import RecruitForm
from SithRecruit.models import Sith, Test, Recruit, Answer, Planet
from SithRecruitSystem.settings import EMAIL_HOST_USER


def recruit(request):
    if request.method == 'POST':
        form = RecruitForm(request.POST)
        if form.is_valid():
            rec = form.save()
            response = redirect('test')
            response.set_cookie('recruit_id', rec.id)
            return response
    else:
        if 'recruit_id' not in request.COOKIES:
            form = RecruitForm()
        else:
            if Recruit.objects.filter(pk=int(request.COOKIES['recruit_id'])).exists():
                form = RecruitForm(
                    initial=model_to_dict(Recruit.objects.get(pk=int(request.COOKIES['recruit_id']))))
            else:
                form = RecruitForm()

    return render(request, 'recruit.html', {'form': form})


def recruits_list(request):
    c = Sith.objects.filter(planet__recruit__master_sith_id=int(request.COOKIES['sith_id'])).count()

    planets = Planet.objects.all()
    planet_id = 0
    if 'planet' not in request.GET or int(request.GET['planet']) == 0:
        recruits = Recruit.objects.filter(master_sith__isnull=True)
    else:
        planet_id = int(request.GET['planet'])
        recruits = Recruit.objects.filter(planet_id=planet_id).filter(master_sith__isnull=True)

    return render(request, 'recruits_list.html',
                  {'recruits': recruits, 'planets': planets, 'planet_id': planet_id, 'count_of_recruits': c})


def test(request):
    if 'recruit_id' not in request.COOKIES:
        return HttpResponse('You are not recruit')
    else:
        rec_id = int(request.COOKIES['recruit_id'])
        rec = Recruit.objects.get(pk=rec_id)
        if rec.answers.count() == 0:
            if request.method == 'POST':
                test_id = str(request.POST['test_id'])
                questions = [x.id for x in Test.objects.get(pk=int(test_id)).questions.all()]
                answers_from_user = [int(x) for x in request.POST if x.isdigit()]
                final_answers = []
                for question_id in questions:
                    final_answers.append(
                        Answer.objects.create(question_id=question_id, answer=question_id in answers_from_user))

                rec = Recruit.objects.get(pk=rec_id)
                rec.answers.set(final_answers)
                rec.save()
                response = redirect('/thank_you')
                response.delete_cookie('recruit_id')
                return response
            else:
                test_for_recruit = Test.objects.get(pk=1)
                questions = test_for_recruit.questions.all()
                return render(request, 'test.html', {'questions': questions, 'test_id': test_for_recruit.id})
        else:
            return HttpResponse('Вы уже прошли испытание')


def thank_you(request):
    return render(request, 'thank_you.html')


def home(request):
    response = render(request, 'home.html')
    response.delete_cookie('sith_id')
    response.delete_cookie('recruit_id')
    return response


def results(request, recruit_id):
    sith_id = 0
    if 'sith_id' in request.COOKIES:
        sith_id = int(request.COOKIES['sith_id'])
    if request.method == 'POST':
        r = Recruit.objects.get(pk=recruit_id)
        count_of_recruits = Recruit.objects.filter(master_sith_id=sith_id).count()
        if count_of_recruits > 2:
            return HttpResponse('У Вас уже есть максимальное число рекрутов')
        r.master_sith = Sith.objects.get(pk=sith_id)
        r.save()
        try:
            send_mail('Набор в орден Ситхов',
                      'Вы успешно прошли испытание и зачислены Рукой Тени',
                      EMAIL_HOST_USER,
                      (r.email,))
        except Exception:
            return HttpResponse('Рекруту не отправлено сообщение о его зачислении. Ошибка почтовой службы')
        else:
            return HttpResponse('Рекруту отправлено сообщение о его зачислении')
    else:
        rec = Recruit.objects.get(pk=recruit_id)
        answers = rec.answers.all()
        count_of_recruits = Recruit.objects.filter(master_sith_id=sith_id).count()
        return render(request, 'results.html',
                      {'recruit': rec, 'answers': answers, 'count_of_recruits': count_of_recruits})


def sith(request):
    if request.method == 'POST':
        response = redirect('recruits_list')
        response.set_cookie('sith_id', request.POST['sith_id'])
        return response
    else:
        if 'shadow_hand_gt_1' in request.GET:
            siths = Sith.objects.raw(
                '''select * from (select sith.*, count(*) as recruit_count
                    from sith
                    join recruit r on sith.id = r.master_sith_id
                    group by sith.id) as s
                    where recruit_count > 1
                ''')
        else:
            siths = Sith.objects.all()
        return render(request, 'sith.html', {'siths': siths})

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Служба рекрутинга ордена Ситхов</title>
</head>
<body>
<h2>Добро пожаловать в Службу рекрутинга ордена Ситхов!</h2>
<div>
    <button>
        <a href="{% url 'sith' %}">
            Вход для Ситхов
        </a>
    </button>
    <button>
        <a href="{% url 'recruit' %}">
            Вход для Рекрутов
        </a>
    </button>
</div>
</body>
</html>

templates/recruit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recruit</title>
</head>
<body>
<form method="post" action="" >
    {% csrf_token %}
    {{ form.as_p }}
        <input type="submit">
</form>
</body>
</html>

templates/recruits_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sith</title>
</head>
<body>
<form method="get">
    <select name="planet" id="planet_select">
        <option value="0" {% if not planet_id or 0 == planet_id %} selected="selected"{% endif %}>Все планеты</option>
        {% for planet in planets %}
            <option value="{{ planet.id }}"
                    {% if planet.id == planet_id %} selected="selected"{% endif %}
            >{{ planet.name }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Выбрать">
</form>
<table>
    <thead>
    <tr>
        <td>Имя</td>
        <td>Возраст</td>
        <td>Email</td>
        <td>Планета</td>
        <td>Ответы</td>
    </tr>
    </thead>
    <tbody>
    {% for recruit in recruits %}
        <tr>
            <td>{{ recruit.name }}</td>
            <td>{{ recruit.age }}</td>
            <td>{{ recruit.email }}</td>
            <td>{{ recruit.planet }}</td>
            <td><a href="{% url 'results' recruit.id %}">Посмотреть ответы</a></td>
        </tr>
        {% empty %}
        <tr>Рекрутов не найдено</tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ответы</title>
</head>
<body>
<h2>Ответы рекрута #{{ recruit.id }}</h2>
<p>Имя: {{ recruit.name }}</p>
<p>Возраст: {{ recruit.age }}</p>
<p>Планета: {{ recruit.planet.name }}</p>
<form method="post">
    {% csrf_token %}
    <table>
        <thead>
        <tr>
            <td>#</td>
            <td>Вопрос</td>
            <td>Ответ</td>
        </tr>
        </thead>
        <tbody>
        {% for answer in answers %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ answer.question }}</td>
                <td>{{ answer.answer }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <input {% if count_of_recruits > 2 %} disabled {% endif %} type="submit" value="Зачислить рекрута Рукой Тени">
    {% if count_of_recruits > 2 %}<p>У вас максимальное число рекрутов</p>{% endif %}
</form>
</body>
</html>

templates/sith.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ситхи</title>
</head>
<body>
<h2>Выберите себя из списка:</h2>
<table>
    <thead>
    <tr>
        <td>#</td>
        <td>Имя</td>
        <td>Планета</td>
        <td>Число Рук Тени</td>
    </tr>
    </thead>
    <tbody>
    {% for sith in siths %}
        <tr style="text-align: center">
            <td>{{ forloop.counter }}</td>
            <td>{{ sith.name }}</td>
            <td>{{ sith.planet }}</td>
            <td>{{ sith.recruit_set.count }}</td>
            <td>
                <form method="post">{% csrf_token %}
                    <input type="submit" value="Выбрать">
                    <input type="hidden" name="sith_id" value="{{ sith.id }}">
                </form>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<form method="get">
    <input type="hidden" name="shadow_hand_gt_1" value="">
    <input type="submit" value="Отобразить Ситхов с числом Рук Теней больше 1">
</form>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
<h3>Ответье на следующие вопросы:</h3>
<form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name="test_id" value="{{ test_id }}">
    {% for i in questions %}
        <p>{{ i.text }}</p>
        <span>Верно?</span>
        <input name="{{ i.id }}" type="checkbox">
    {% endfor %}
    <div style="padding-top: 10px"><input type="submit" title="Отправить"></div>
</form>
</body>
</html>

templates/thank_you.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Спасибо</title>
</head>
<body>
<h2>Спасибо! Мы Вам перезвоним.</h2>
<a href="/">
    <button>На главную</button>
</a>
</body>
</html>